route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: malkinfedor@gmail.com
    from: kerios4fedor@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "kerios4fedor@gmail.com"
    auth_identity: "kerios4fedor@gmail.com"
    auth_password: "qqnykdgyxdufnwln"
    send_resolved: true

#global:
#  resolve_timeout: 5m

#route:
#  group_by: ['alertname']
#  group_wait: 10s
#  group_interval: 10s
#  repeat_interval: 1h
#  receiver: 'web.hook'
#receivers:
#- name: 'web.hook'
#  webhook_configs:
#  - url: 'http://127.0.0.1:5001/'
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#   # equal: ['alertname', 'dev', 'instance']
