# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 10.0.0.4:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files: 
    - alert_rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
    - targets: ['10.0.0.4:9100']

  - job_name: 'ms-build'
    static_configs:
    - targets: ['ms-build.westeurope.cloudapp.azure.com:9182']

  - job_name: blackbox_http_no_auth
    params:
      module:
      - http_2xx
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /probe
    scheme: http
    static_configs:
    - targets:
      - https://api-ip.fssprus.ru/api/v1.0
      - https://tracking.pochta.ru/tracking-web-static/fc_wsdl.xml
    relabel_configs:
    - source_labels: [__address__]
      separator: ;
      regex: (.*)
      target_label: __param_target
      replacement: $1
      action: replace
    - source_labels: [__param_target]
      separator: ;
      regex: (.*)
      target_label: instance
      replacement: $1
      action: replace
    - separator: ;
      regex: (.*)
      target_label: __address__
      replacement: ms-build.westeurope.cloudapp.azure.com:9115
      action: replace

