global:
 scrape_interval: 5s
 evaluation_interval: 10s
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager-1:9093', 'alertmanager-2:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - alert_rules.yml

scrape_configs:
 - job_name: prometheus
   static_configs:
     - targets: ['localhost:9090']
 - job_name: linux_basic
   static_configs:
     - targets: ['ansibleclient:9100']

remote_write:
 - url: "http://prometheus_postgresql_adapter_1:9201/write"
remote_read:
 - url: "http://prometheus_postgresql_adapter_1:9201/read"
   read_recent: true
