global:
 scrape_interval: 5s
 evaluation_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
     - targets: ['localhost:9091']
 - job_name: linux_basic
   static_configs:
     - targets: ['node_exporter:9100']

remote_write:
 - url: "http://prometheus_postgresql_adapter_2:9202/write"
remote_read:
 - url: "http://prometheus_postgresql_adapter_2:9202/read"
   read_recent: true
